[tool.poetry]
name = "pythonproject66"
version = "0.1.0"
description = ""
authors = ["kseno <ksenox.moroz.2000@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
